### ISSUE TITLE
Bring back fancy snippets

### ISSUE THREAD

**Issue by b2vn** [zyxar/Sublime-CMakeLists#47]
I have not been able to get snippets and auto completion to work after #44. Please update the README with instruction on how to setup the plugin.

**Comment by rwols** [comment]
Could you please run `View Package File` from the Command Palette and see if `CMake/CMake.sublime-completions` exists?

**Comment by b2vn** [comment]
I just reinstalled a fresh ubuntu in vmware. Only thing on the computer is, ubuntu 20.04 + followed the installation guide from sublime text web site + installed the 'cmake' plugin from package control.

As requested, validated that `CMake/CMake.sublime-completions` exists (the file is a json in a single line, 8261 characters long).
![image](https://user-images.githubusercontent.com/12070493/102068265-89547a80-3dfc-11eb-90b1-7a66f1893e4e.png)

I created a new `CMakeLists.txt` and start to type. I do get the list of commands.
![image](https://user-images.githubusercontent.com/12070493/102068757-231c2780-3dfd-11eb-9b5f-61bcd97f0ab1.png)

... but when I select one of them, the command arguments are not filled as in previous versions of the plugin.
![image](https://user-images.githubusercontent.com/12070493/102068633-f9630080-3dfc-11eb-8ff0-2ec542036ed8.png)

**Comment by rwols** [comment]
I simplified the snippets, but I'm noticing now that some of the bespoke snippets were indeed useful. I'll add them back when I have some free time.

**Comment by arcturus140** [comment]
i am new here. Found this after reading the change notes. Is there an existing discussion about the introduction of this change? None of the snippets open brackets, this is very unconventional.

**Comment by rwols** [comment]
Fixed in 523b5f580c553f0c3507afe76d1c6b0276fab66f

**Comment by b2vn** [comment]
Hmm, there still seen be something off. The built in constants are still not working, e.g. `${PROJECT_NAME}`.

I think the snippets you added seem to be great. I currently run the plugin from master but checkout `AutoComplete.py` from 2cbf9c5.
